from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

from .config import experiment_output_dir, load_config, resolve_path
from .data import validate_data_storage
from .oracle import selection_mode
from .prepare_biwi import (
    EXPECTED_ACCEPTED_FRAMES,
    EXPECTED_ACCEPTED_SAMPLE_IDS_SHA256,
    FSA_NET_BIWI_PROTOCOL,
)
from .utils import sha256_file


def _read_summary(manifest: Path) -> dict[str, Any]:
    summary_path = manifest.with_suffix(".summary.json")
    if not summary_path.is_file():
        raise FileNotFoundError(f"Missing manifest summary: {summary_path}")
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    actual_hash = sha256_file(manifest)
    expected_hash = str(
        summary.get("sha256", summary.get("manifest_sha256", ""))
    ).lower()
    if actual_hash.lower() != expected_hash:
        raise RuntimeError(
            f"Manifest SHA256 mismatch for {manifest}: "
            f"expected {expected_hash}, got {actual_hash.lower()}."
        )
    with manifest.open("r", encoding="utf-8") as handle:
        count = sum(1 for line in handle if line.strip())
    if count != int(summary.get("accepted", -1)):
        raise RuntimeError(
            f"Manifest count mismatch for {manifest}: "
            f"summary={summary.get('accepted')}, lines={count}."
        )
    return {
        "path": str(manifest),
        "sha256": actual_hash,
        "accepted": count,
        "protocol": summary.get("protocol"),
        "accepted_sample_ids_sha256": summary.get("accepted_sample_ids_sha256"),
    }


def _check_model(config: dict[str, Any]) -> dict[str, Any]:
    model = config["model"]
    kind = str(model["kind"]).lower()
    result: dict[str, Any] = {"kind": kind}
    if kind == "dime":
        resolve_path(model["dime_source"], must_exist=True)
        checkpoint = resolve_path(model.get("pretrained_checkpoint"), must_exist=True)
    elif kind == "repvgg":
        resolve_path(model["repo"], must_exist=True)
        checkpoint = resolve_path(model.get("pretrained_checkpoint"), must_exist=True)
    elif kind in {"dino", "mae"}:
        value = str(model.get("pretrained_checkpoint", "")).strip()
        checkpoint = resolve_path(value, must_exist=True) if value else None
        result["weight_source"] = (
            "local checkpoint" if checkpoint else "timm shared cache"
        )
    else:
        raise ValueError(f"Unsupported controlled model kind: {kind}")

    if checkpoint is not None:
        actual_hash = sha256_file(checkpoint)
        expected_hash = str(model.get("expected_pretrained_sha256", "")).strip().lower()
        if expected_hash and actual_hash.lower() != expected_hash:
            raise RuntimeError(
                f"Checkpoint SHA256 mismatch for {checkpoint}: "
                f"expected {expected_hash}, got {actual_hash.lower()}."
            )
        result.update({"checkpoint": str(checkpoint), "sha256": actual_hash})
    return result


def check_config(
    config_path: Path,
    *,
    seeds: list[int],
    manifest_cache: dict[Path, dict[str, Any]],
) -> dict[str, Any]:
    config = load_config(config_path)
    configured_selection = selection_mode(config)
    wandb = config.get("wandb", {})
    if (
        bool(wandb.get("enabled", True))
        and str(wandb.get("mode", "online")).lower() == "online"
    ):
        api_key_env = str(wandb.get("api_key_env", "WANDB_API_KEY"))
        configured_api_key = str(wandb.get("api_key", "")).strip()
        if not configured_api_key and not os.environ.get(api_key_env, "").strip():
            raise RuntimeError(
                "W&B credentials are missing: set wandb.api_key or "
                f"{api_key_env} for {config_path}."
            )
    data = config["data"]
    manifests = {
        "train": resolve_path(data["train_manifest"], must_exist=True),
        "aflw2000": resolve_path(data["aflw2000_manifest"], must_exist=True),
        "biwi": resolve_path(data["biwi_manifest"], must_exist=True),
    }
    storage = validate_data_storage(config, ("train", "aflw2000", "biwi"))

    checked_manifests: dict[str, dict[str, Any]] = {}
    for split, manifest in manifests.items():
        assert manifest is not None
        if manifest not in manifest_cache:
            manifest_cache[manifest] = _read_summary(manifest)
        checked_manifests[split] = manifest_cache[manifest]
    if checked_manifests["biwi"]["protocol"] != FSA_NET_BIWI_PROTOCOL:
        raise RuntimeError(
            "BIWI manifest was not generated by the pinned FSA-Net protocol: "
            f"expected {FSA_NET_BIWI_PROTOCOL!r}, got "
            f"{checked_manifests['biwi']['protocol']!r}."
        )
    if checked_manifests["biwi"]["accepted"] != EXPECTED_ACCEPTED_FRAMES:
        raise RuntimeError(
            "BIWI accepted-count mismatch for the controlled table: "
            f"expected {EXPECTED_ACCEPTED_FRAMES}, got "
            f"{checked_manifests['biwi']['accepted']}."
        )
    if (
        checked_manifests["biwi"]["accepted_sample_ids_sha256"]
        != EXPECTED_ACCEPTED_SAMPLE_IDS_SHA256
    ):
        raise RuntimeError(
            "BIWI accepted sample membership does not match the official "
            "FSA-Net BIWI_noTrack.npz artifact: expected "
            f"{EXPECTED_ACCEPTED_SAMPLE_IDS_SHA256}, got "
            f"{checked_manifests['biwi']['accepted_sample_ids_sha256']}."
        )

    collisions = [
        str(experiment_output_dir(config, seed))
        for seed in seeds
        if experiment_output_dir(config, seed).exists()
    ]
    if collisions:
        raise FileExistsError(
            "Fresh benchmark output directories already exist; move them or use "
            f"the explicit resume flow: {collisions}"
        )

    return {
        "config": str(config_path),
        "experiment": config["experiment"]["name"],
        "model": _check_model(config),
        "selection": configured_selection,
        "storage": storage,
        "manifests": checked_manifests,
        "seeds": seeds,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fail-fast validation before submitting the controlled benchmark."
    )
    parser.add_argument("--configs", type=Path, nargs="+", required=True)
    parser.add_argument("--seeds", type=int, nargs="+", default=[0])
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cache: dict[Path, dict[str, Any]] = {}
    results = [
        check_config(
            path.expanduser().resolve(), seeds=args.seeds, manifest_cache=cache
        )
        for path in args.configs
    ]
    print(json.dumps({"status": "ok", "configs": results}, indent=2))


if __name__ == "__main__":
    main()
